layer_height: 0.05
material_num: 2
img_path_0: C:/Users/82653/Desktop/model/black/
img_path_1: C:/Users/82653/Desktop/model/white/
img_path_2: C:/Users/82653/Desktop/model/white/
back_distance: 5
bottom_layers: 3
bottom_exposure_time_0: 5
bottom_exposure_current_0: 40
standard_exposure_time_0: 0.8
standard_exposure_current_0: 40
bottom_exposure_time_1: 5
bottom_exposure_current_1: 40
standard_exposure_time_1: 0.8
standard_exposure_current_1: 40
bottom_exposure_time_2: 5
bottom_exposure_current_2: 40
standard_exposure_time_2: 0.8
standard_exposure_current_2: 40
max_height: 150
min_height: -50
z_acc_h: 100
z_dec_h: -100
z_speed_h: 100
z_acc_l: 50
z_dec_l: -50
z_speed_l: 50
r_acc: 60
r_dec: -60
r_speed: 60
clean_tank: 3
clean_tank_height: 20
clean_height: 50
clean_height_coefficient: 1.0
clean_times: 3
clean_time: 3.0
clean_distance: 10
dry_tank: 4
dry_height: 70
dry_time_bottom: 100
dry_time_standard: 40
pre_z_height: 10
drop_time_bottom: 20
drop_layers_bottom: 20
drop_time_standard: 5
ASS: False
ASS_volume: 550
ASS_times: 20
AMS: True
AMS_layers: 30
AMS_tank_offset: 2.5
AMS_volume: 20
lapse: False
lapse_height: 150
lapse_tank: 0