# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_slice.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1083, 775)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1081, 771))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.sliceTab = QtWidgets.QWidget()
        self.sliceTab.setObjectName("sliceTab")
        self.sliceButton = QtWidgets.QPushButton(self.sliceTab)
        self.sliceButton.setGeometry(QtCore.QRect(830, 580, 151, 81))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.sliceButton.setFont(font)
        self.sliceButton.setObjectName("sliceButton")
        self.configEdit = QtWidgets.QTextEdit(self.sliceTab)
        self.configEdit.setGeometry(QtCore.QRect(50, 80, 741, 651))
        self.configEdit.setObjectName("configEdit")
        self.openConfigButton = QtWidgets.QPushButton(self.sliceTab)
        self.openConfigButton.setGeometry(QtCore.QRect(830, 200, 151, 81))
        self.openConfigButton.setObjectName("openConfigButton")
        self.saveConfigButton = QtWidgets.QPushButton(self.sliceTab)
        self.saveConfigButton.setGeometry(QtCore.QRect(830, 360, 151, 81))
        self.saveConfigButton.setObjectName("saveConfigButton")
        self.configPath = QtWidgets.QLabel(self.sliceTab)
        self.configPath.setGeometry(QtCore.QRect(50, 20, 911, 41))
        self.configPath.setObjectName("configPath")
        self.tabWidget.addTab(self.sliceTab, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sliceButton.setText(_translate("Form", "切 片"))
        self.openConfigButton.setText(_translate("Form", "打开配置"))
        self.saveConfigButton.setText(_translate("Form", "保存配置"))
        self.configPath.setText(_translate("Form", "None"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sliceTab), _translate("Form", "切片"))
